### PR TITLE
`bbin ls` prints human readable text

### PR DESCRIPTION
**Pull request by eval**
Please answer the following questions and leave the below in as part of your PR.

- [X] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
  - #53
- [x] update docs

Example:
Screenshot 2023-02-07 at 18 48 20

Feedback welcome.

### CODE REVIEW

**Comment by borkdude** [comment]
@eval That looks pretty sweet to me!

@rads What do you think?

**Comment by rads** [comment]
Thanks for the PR. I'll take a look at this soon.

**Comment by rads** [comment]
@eval @borkdude: It looks like we have some challenges with smaller screen widths. [Here's what the new version looks like](https://user-images.githubusercontent.com/11401/222920962-f189939b-7d56-4792-9a23-b8194472bc52.png) on my MacBook Air.

We can try to fix this problem within `bbin`, however before we go too far down the rabbit hole, would this code make more sense as a standalone library to convert EDN to CLI tables? If we were using `nbb` I'd pull in [cli-table3](https://github.com/cli-table/cli-table3)... maybe it would be useful to have a similar lib for `bb`?

**Review by rads — CHANGES_REQUESTED** [review]
Need a solution for readable output when small screen widths and long URLs are involved.

**Comment by rads** [comment]
After thinking about this a bit more, I wonder if we should replace the table with something simpler and more compact. For example, here's the output of `npm ls`:
```
$ npm --location=global ls
/Users/rads/.nvm/versions/node/v16.16.0/lib
├── npm@8.11.0
├── sql-formatter@12.1.2
├── squint-cljs@0.0.10
```

We could do something similar (the `*` represents bold text):

```
*hello* (tag: 594ffad)
*neil* (tag: v0.1.56)
*bbin-dev* (url: file:///Users/rads/src/bbin)
```

Or a more extended version:
```
*hello (ht.sr.rads/watch-private)*
URL: git@git.sr.ht:~rads/watch-private
SHA: 594ffadceea43313789f85a42a120791ce35e323

*neil (io.github.babashka/neil)*
URL: https://github.com/babashka/neil.git
Tag: v0.1.56
SHA: abea182499897eda40088d24b647e66099ef94ed

*bbin-dev*
URL: file:///Users/rads/src/bbin
```

What do you think?

**Comment by borkdude** [comment]
Maybe it would make more sense to print like neil: in general the output if neil can be piped back into neil subcommands.

E.g.:

```
bbin ls

:name "foo" :location ... 
:name "bar" :location ...
```

and

**Comment by rads** [comment]
@borkdude: That sounds good to me.

**Comment by eval** [comment]
My vote goes to 'team human(-readable)', and make this listing easy on the eyes.

So alternatively, using this PR, we'll squash columns `bbin/url`, `git/url` and `local/root` into one column `location`, and columns `git/sha` and `git/tag` into `version`:
Screenshot 2023-03-10 at 15 48 52

**Comment by borkdude** [comment]
It sure is pretty

**Comment by rads** [comment]
@eval: When I split my terminal on my MacBook Air with my current font size, I get 71 characters horizontally. If we can get it to work without wrapping in 71 characters then I'm open to merging this PR in. This will require truncation since URLs are often much longer than 71 characters plus each column needs its own space.

**Comment by rads** [comment]
@eval: I appreciate your patience so far. I'm planning to do a final review this week. I'll put the new functionality behind a flag until I release `0.2.0` since it's technically a breaking change. This will coincide with #34 which is another breaking change (and my next priority on the list of issues).

**Comment by rads** [comment]
Woops, I meant to link to #35 instead of #34.

**Review by rads — APPROVED** [review]

**Pull request merged**
